version: '3'

services:
  spring:
    build:
      context: .
      dockerfile: spring.dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - desafio-dev
    restart: on-failure

  postgres:
    image: postgres:9.4
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=banco
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - desafio-dev

networks:
  desafio-dev:
    driver: bridge
